services:
  #  selenium-hub:
  #    image: selenium/hub:latest
  #    container_name: selenium-hub
  #    ports:
  #      - "4442:4442"
  #      - "4443:4443"
  #      - "4444:4444"
  #    networks:
  #      - grid
  #    restart: on-failure  # Restart only on failure
  #
  #  chrome:
  #    image: selenium/node-chrome:latest
  #    depends_on:
  #      - selenium-hub
  #    shm_size: "2g"
  #    environment:
  #      - SE_EVENT_BUS_HOST=selenium-hub
  #      - SE_EVENT_BUS_PUBLISH_PORT=4442
  #      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #    networks:
  #      - grid
  #    restart: on-failure

  #  edge:
  #    image: selenium/node-edge:latest
  #    depends_on:
  #      - selenium-hub
  #    shm_size: "2g"
  #    environment:
  #      - SE_EVENT_BUS_HOST=selenium-hub
  #      - SE_EVENT_BUS_PUBLISH_PORT=4442
  #      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #    networks:
  #      - grid
  #    restart: on-failure
  #
  #  firefox:
  #    image: selenium/node-firefox:latest
  #    depends_on:
  #      - selenium-hub
  #    shm_size: "2g"
  #    environment:
  #      - SE_EVENT_BUS_HOST=selenium-hub
  #      - SE_EVENT_BUS_PUBLISH_PORT=4442
  #      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #    networks:
  #      - grid
  #    restart: on-failure

  elasticsearch:
    image: elasticsearch:8.17.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - grid
    restart: unless-stopped

  kibana:
    image: kibana:8.17.4
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - grid
    restart: unless-stopped
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

networks:
  grid:

volumes:
  elasticsearch-data: