package com.rdb.enums;

public enum ConfigProperties {

    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSCREENSHOT,
    FAILEDSTEPSCREENSHOT,
    SKIPPEDSTEPSCREENSHOT,
    RUNMODE,
    SENDLOGSTOELK,
    SELENIUMCOMMANDTIMEOUT,
    PAGELOADWAITTIME,
    RETRYFAILEDTESTS;

}
